SOLVER:
  gpu: 0,
  logdir: logs/ae/0327_ocnn
  run: train
  max_iter: 320000
  test_iter: 336
  test_every_iter: 2000
  step_size: (80000,)

DATA:
  train:
    dtype: octree
    depth: 6
    location: dataset/completion_train_octree_6_lmdb_new.tfrecord 
    batch_size: 16
    x_alias: octree # be careful with this parameter
  test: 
    dtype: octree
    depth: 6
    location: dataset/completion_test_octree_6_lmdb_new.tfrecord
    shuffle: 0
    batch_size: 16
    x_alias: octree # be careful with this parameter

MODEL:
  name: ocnn
  channel: 4
  nout: 256   # the hidden code
  depth: 6

LOSS:
  weight_decay: 0.0005