SOLVER:
  gpu: 0,
  logdir: logs/ae/0322_ocnn_test
  ckpt: logs/ae/0322_ocnn/model/iter_320000.ckpt
  run: decode_shape
  max_iter: 320000
  test_iter: 100

DATA:
  test: 
    dtype: octree
    depth: 6
    location: dataset/completion_test_octree_6_lmdb_new.tfrecord
    shuffle: 0
    batch_size: 1
    x_alias: octree # be careful with this parameter

MODEL:
  name: ocnn
  channel: 4
  nout: 128   # the hidden code
  depth: 6

LOSS:
  num_class: 40
  weight_decay: 0.0005