# Parameters for the airplane

SOLVER:
  gpu: 0,
  logdir: logs/seg/02691156_airplane
  run: train
  max_epoch: 300
  test_every_epoch: 5
  step_size: (120,180,240)
  ckpt_num: 20

DATA:
  train:
    distort: True
    depth: 6
    angle: (0, 5, 0)
    interval: (1, 1, 1)
    scale: 0.25
    jitter: 0.25
    uniform: True
    node_dis: True
    location: dataset/shapenet_segmentation/points
    filelist: dataset/shapenet_segmentation/train_test_split/02691156_train_val.txt
    batch_size: 32

  test: 
    distort: False  # no data augmentation
    depth: 6
    node_dis: True
    location: dataset/shapenet_segmentation/points
    filelist: dataset/shapenet_segmentation/train_test_split/02691156_test.txt
    batch_size: 1

MODEL:
  name: segnet
  channel: 4
  nout: 4
  depth: 6
  depth_out: 6

LOSS:
  num_class: 4
  weight_decay: 0.0005
